services:
  app:
    build: .
    volumes:
      - type: bind
        source: /home/think/aq/temp2
        target: /etc/temp
    environment:
      database_dbname: "gorm.db"
      monitor_dirpath: "/etc/temp"
